name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Login to Azure
        if: github.ref == 'refs/heads/main'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          az acr build --registry ${{ secrets.AZURE_REGISTRY }} --image app:${{ github.sha }} .

      - name: Deploy to Azure Container Instances
        if: github.ref == 'refs/heads/main'
        run: |
          az container create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name app-${{ github.sha }} --image ${{ secrets.AZURE_REGISTRY }}.azurecr.io/app:${{ github.sha }}